#!/usr/bin/env bash
# Validate a commit message: Conventional Commits subject + no attribution.
# Usage: check-msg.sh <message-file>   (or pipe the message on stdin)
# Exit 0 = clean & well-formed; exit 1 = problems (printed to stderr).
set -euo pipefail

if [[ $# -ge 1 && "$1" != "-" ]]; then
  msg="$(cat -- "$1")"
else
  msg="$(cat)"
fi

subject="$(printf '%s\n' "$msg" | head -1)"
status=0

# 1. No authorship or tooling attribution anywhere in the message.
if printf '%s\n' "$msg" | grep -Eiq '^co-authored-by:'; then
  echo "ERROR: message contains a Co-Authored-By trailer; remove it." >&2
  status=1
fi
if printf '%s\n' "$msg" | grep -Eiq 'generated with|generated by'; then
  echo "ERROR: message contains generation attribution; remove it." >&2
  status=1
fi

# 2. Conventional Commits subject.
pattern='^(feat|fix|perf|refactor|docs|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?!?: .+'
if ! [[ "$subject" =~ $pattern ]]; then
  echo "ERROR: subject is not Conventional Commits:" >&2
  echo "  '$subject'" >&2
  echo "  expected: <type>(<scope>): <description>" >&2
  echo "  types: feat fix perf refactor docs test build ci chore revert" >&2
  status=1
fi

# 3. Subject length advisory (non-fatal).
if (( ${#subject} > 72 )); then
  echo "WARN: subject is ${#subject} chars (recommended <= 72)." >&2
fi

[[ $status -eq 0 ]] && echo "OK: $subject"
exit $status
